baseurl: "/"
title: "Java Dev Podcast"
footnotereturnlinkcontents: "â†©"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
uglyURLs: false
metaDataFormat: "yaml"
params:
  itunes: https://itunes.apple.com/podcast/id123456789
  android: /index.xml
  feed: /index.xml
permalinks:
  post: "/:title"
