baseurl: "https://1000ch.github.io/hugo-boilerplate-podcast"
title: "hugo-boilerplate-podcast"
footnotereturnlinkcontents: "â†©"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
uglyURLs: false
metaDataFormat: "yaml"
params:
  itunes: https://itunes.apple.com/podcast/id123456789
  android: http://subscribeonandroid.com/1000ch.github.io/hugo-boilerplate-podcast/index.xml
  feed: https://1000ch.github.io/hugo-boilerplate-podcast/index.xml
permalinks:
  post: "/:title"
